
import Foundation

struct placesStruct {
    var name: String
    var textAbout: String
    var photo: String
    var latitude: String
    var longitude: String
    init(name: String, textAbout: String, photo: String, latitude: String, longitude: String ) {
        self.name = name
        self.photo = photo
        self.latitude = latitude
        self.longitude = longitude
        self.textAbout = textAbout
    }
}


var arrayPlaces = [
    placesStruct(name: "The Art Institute of Chicago", textAbout: "  See why the Art Institute of Chicago is the only museum in the world to be top-ranked by TripAdvisor four years in a row! Experience the greatest Impressionist collection outside Paris, and view contemporary masterpieces in the spectacular Modern Wing. Stand before classics like Nighthawks, and travel the globe through galleries devoted to the art of ancient Greece, Japan, Africa, and the Americas.",  photo: "The Art Institute of Chicago", latitude: "41.879628", longitude: "-87.624142"),
    placesStruct(name: "Millennium Park", textAbout: "  Millennium Park is a public park located in the Loop community area of Chicago in Illinois operated by the Chicago Department of Cultural Affairs and managed by MB Real Estate. The park was originally intended to celebrate the third millennium and is a prominent civic center near the city's Lake Michigan shoreline that covers a 24.5-acre (99,000 m2) section of northwestern Grant Park. The area was previously occupied by parkland, Illinois Central's rail yards, and parking lots. The park, which is bounded by Michigan Avenue, Randolph Street, Columbus Drive and East Monroe Drive, features a variety of public art. ",  photo: "Millennium Park", latitude: "41.882685", longitude: "-87.620281"),
    placesStruct(name: "Museum of Science and Industry", textAbout: "The largest science museum in the Western Hemisphere! Housed in the only remaining building from the 1893 World’s Fair, MSI is a Chicago must-see. You’ll experience 14 acres of hands-on exhibits and have the chance to stand before a 40-foot tornado; climb aboard a World War II German submarine; take a run in a human-sized hamster wheel; descend into an Illinois coal mine; tour a fully functioning eco-friendly home; board a 727 hanging from the ceiling; transmit your pulse to a 13-foot, 3-D beating heart; and much more!",  photo: "Museum of Science and Industry", latitude: "41.789941", longitude: "-87.582884"),
    placesStruct(name: "360 Chicago Observation Deck", textAbout: "  Located on the 94th floor of the John Hancock Center, 360 CHICAGO offers breathtaking views of Chicago’s skyline, the lakefront, and four states. It’s the only place you can enjoy Chicago’s highest thrill ride, TILT – a giant moving platform that literally TILTs visitors over the edge of the building. Relax at BAR 94 with local favorites, a large cocktail selection, and front-row seating to the city’s best views from 1,000 feet up. Explore HD interactive touch screens in seven languages and learn more about the Windy City.", photo: "360 Chicago Observation Deck", latitude: "41.898833", longitude: "-87.623774"),
    placesStruct(name: "Cloud Gate", textAbout: "  Cloud Gate is a public sculpture by Indian-born British artist Sir Anish Kapoor, that is the centerpiece of AT&T Plaza at Millennium Park in the Loop community area of Chicago, Illinois. The sculpture and AT&T Plaza are located on top of Park Grill, between the Chase Promenade and McCormick Tribune Plaza & Ice Rink. Constructed between 2004 and 2006, the sculpture is nicknamed The Bean because of its shape. Made up of 168 stainless steel plates welded together, its highly polished exterior has no visible seams. It measures 33 by 66 by 42 feet (10 by 20 by 13 m), and weighs 110 short tons (100 t; 98 long tons).",  photo: "Cloud Gate", latitude: "41.882657", longitude: "-87.623458"),
    placesStruct(name: "Wrigley Field", textAbout: "  Wrigley Field /ˈrɪɡli/ is a baseball park located on the North Side of Chicago, Illinois. It is the home of the Chicago Cubs, one of the city's two Major League Baseball (MLB) franchises. It first opened in 1914 as Weeghman Park for Charles Weeghman's Chicago Whales of the Federal League, which folded after the 1915 baseball season. The Cubs played their first home game at the park on April 20, 1916, defeating the Cincinnati Reds with a score of 7–6 in 11 innings. Chewing gum magnate William Wrigley Jr. of the Wrigley Company acquired complete control of the Cubs in 1921.",  photo: "Wrigley Field", latitude: "41.947373", longitude: "-87.656423"),
    placesStruct(name: "Field Museum", textAbout: "  The Field Museum of Natural History (FMNH), also known as The Field Museum, is a natural history museum in Chicago, and is one of the largest such museums in the world. The museum maintains its status as a premier natural-history museum through the size and quality of its educational and scientific programs, as well as due to its extensive scientific-specimen and artifact collections. The diverse, high-quality permanent exhibitions, which attract up to two million visitors annually, range from the earliest fossils to past and current cultures from around the world.",  photo: "Field Museum", latitude: "41.865416", longitude: "-87.617080"),
    placesStruct(name: "Chicago Riverwalk", textAbout: "  The Chicago Riverwalk is an open, pedestrian waterfront located on the south bank of the main branch of the Chicago River in downtown Chicago, Illinois managed by MB Real Estate. It spans from Lake Shore Drive to Lake Street. Called the city's 'Second Lakefront', the Riverwalk contains restaurants, park-seating, boat rentals, and other activities. Its current and planned final extent was opened to Wolf Point in 2017. In conjunction with the Chicago Department of Transportation, construction of the Riverwalk began in 2001 as an extension of the Wacker Drive reconstruction project. ",  photo: "Chicago Riverwalk", latitude: "41.888342", longitude: "-87.621844"),
    placesStruct(name: "The Magnificent Mile", textAbout: "  The Magnificent Mile is one of the great avenues of the world and is at the center of all that makes Chicago an international destination. One of the top 10 hospitality, dining and retail destinations in the world, with endless shopping, international cuisine, top rated hotels, lively entertainment, majestic architecture and natural beauty at every turn, The Magnificent Mile offers visitors to Chicago a one-of-a-kind city experience. The Magnificent Mile is the 13-block stretch of North Michigan Avenue that runs from the banks of the Chicago River to the south, to Oak Street to the north.",  photo: "The Magnificent Mile", latitude: "41.889256", longitude: "-87.624161"),
    placesStruct(name: "Chicago Cultural Center", textAbout: "  The Chicago Cultural Center, opened in 1897, is a Chicago Landmark building operated by Chicago's Department of Cultural Affairs and Special Events that houses the city's official reception venue where the Mayor of Chicago has welcomed Presidents and royalty, diplomats and community leaders. It is located in the Loop, across Michigan Avenue from Millennium Park. Originally the central library building, it was converted in 1977 to an arts and culture center at the instigation of Commissioner of Cultural Affairs Lois Weisberg.",  photo: "Chicago Cultural Center", latitude: "41.883712", longitude: "-87.624684"),
    placesStruct(name: "Lincoln Park Zoo", textAbout: "  Lincoln Park Zoo is a 35-acre (14 ha) zoo located in Lincoln Park in Chicago, Illinois. The zoo was founded in 1868, making it among the oldest zoos in North America. It is also one of a few free admission zoos in the United States. The zoo is an accredited member of the Association of Zoos and Aquariums (AZA).Lincoln Park Zoo is home to a wide variety of animals. The zoo's exhibits include big cats, polar bears, penguins, gorillas, reptiles, monkeys, and other species totaling about 1,100 animals from some 200 species.",  photo: "Lincoln Park Zoo", latitude: "41.921102", longitude: "-87.633871"),
    placesStruct(name: "Lakefront Trail", textAbout: "  The Chicago Lakefront Bicycle Trail is roughly 22 miles of bike paths, stretching from Indiana border up to Evanston. The trail rides through many parks including Jackson Park (including U of Chicago), Grant Park (including Buckingham Fountain/Museum Campus) Millennium Park, and Lincoln Park with its Free Zoo. Plenty of beaches and bike rentals available at Bobby's Bike Hike - 540 N. Lake Shore Drive, Chicago IL 60611 (free maps, helmets).",  photo: "Lakefront Trail", latitude: "41.876631", longitude: "-87.616514"),
    placesStruct(name: "Richard H. Driehaus Museum", textAbout: "  The Richard H. Driehaus Museum is a museum located at 40 East Erie Street on the Near North Side in Chicago, Illinois, near the Magnificent Mile. The museum is housed within the historic Samuel M. Nickerson House, the 1883 residence of a wealthy Chicago banker. Although the mansion has been restored, the Driehaus Museum does not re-create the Nickerson period but rather broadly interprets and displays the prevailing design, architecture, and decorating tastes of Gilded Age America and the art nouveau era in permanent and special exhibitions.",  photo: "Richard H. Driehaus Museum", latitude: "41.894171", longitude: "-87.626666"),
    placesStruct(name: "Shedd Aquarium", textAbout: "  Shedd Aquarium (formally the John G. Shedd Aquarium) is an indoor public aquarium in Chicago, Illinois, in the United States. Opened on May 30, 1930, the 5,000,000 US gal (19,000,000 l; 4,200,000 imp gal) aquarium was for some time the largest indoor facility in the world. Today it holds some 32,000 animals.Shedd Aquarium was the first inland aquarium with a permanent saltwater fish collection. It is located on Lake Michigan, on the Museum Campus Chicago, along with the Adler Planetarium and the Field Museum of Natural History.In 2015, the aquarium had 2.02 million visitors.",  photo: "Shedd Aquarium", latitude: "41.866962", longitude: "-87.613511"),
    placesStruct(name: "Buckingham Fountain", textAbout: "  Buckingham Fountain is a Chicago landmark in the center of Grant Park. Dedicated in 1927, it is one of the largest fountains in the world. Built in a rococo wedding cake style and inspired by the Latona Fountain at the Palace of Versailles, it is meant to allegorically represent Lake Michigan. It operates from April to October, with regular water shows and evening color-light shows. During the winter, the fountain is decorated with festival lights. The fountain is considered Chicago's front door, since it resides in Grant Park, the city's front yard near the intersection of Columbus Drive and Ida B. Wells Drive.",  photo: "Buckingham Fountain", latitude: "41.875984", longitude: "-87.619726"),
    placesStruct(name: "Garfield Park Conservatory", textAbout: "  Garfield Park Conservatory, located in Garfield Park in Chicago is one of the largest greenhouse conservatories in the United States. Often referred to as 'landscape art under glass', the Garfield Park Conservatory occupies approximately 4.5 acres (18,000 m2) inside and out and contains a number of permanent plant exhibits incorporating specimens from around the world, including some cycads that are over 200 years old.Along with the Lincoln Park Conservatory on Chicago's north side, the Garfield Park Conservatory provides significant horticultural collections, educational programs and community outreach efforts.",  photo: "Garfield Park Conservatory", latitude: "41.886165", longitude: "-87.716790"),
    placesStruct(name: "United Center", textAbout: "  United Center is an indoor arena on the Near West Side of Chicago, Illinois, United States. It is home to the Chicago Bulls of the National Basketball Association (NBA) and the Chicago Blackhawks of the National Hockey League (NHL), named after its corporate sponsor, United Airlines.The United Center's predecessor, the Chicago Stadium, was demolished after the new arena opened in 1994. The first event at the United Center was the WWF SummerSlam. Due to a lockout, the Blackhawks did not move in until the 1994-95 NHL season.",  photo: "United Center", latitude: "41.880372", longitude: "-87.675038"),
    placesStruct(name: "Skydeck Chicago - Willis Tower", textAbout: "  No trip to Chicago is complete without a visit to the top of the tallest building in the Western Hemisphere and The Ledge at Skydeck Chicago! Treat yourself to a 'one stop Chicago' experience on your journey to the 103rd floor. Enjoy 360-degree views spanning up to 50 miles and 4 states and our most spectacular view - 1,353 feet straight down! 'Dare to Stand Out' on The Ledge - glass balconies extending 4.3 Feet outside the building provide a thrilling, once in a lifetime experience!",  photo: "Skydeck Chicago - Willis Tower", latitude: "41.879217", longitude: "-87.635938"),
    placesStruct(name: "Maggie Daley Park", textAbout: "  Maggie Daley Park is a 20-acre (81,000 m2) public park in the Loop community area of Chicago operated by the Chicago Park District and managed by MB Real Estate. It is near the Lake Michigan shoreline in northeastern Grant Park where Daley Bicentennial Plaza previously stood. Maggie Daley Park, like its predecessor, is connected to Millennium Park by the BP Pedestrian Bridge. Designed by landscape architect Michael Van Valkenburgh, the park had its ceremonial ribbon cutting on December 13, 2014, and is named for Maggie Daley, the former first lady of the city who died of cancer in 2011.",  photo: "Maggie Daley Park", latitude: "41.882129", longitude: "-87.618974"),
    placesStruct(name: "The Loop", textAbout: "  The Loop, one of Chicago's 77 designated community areas, is the central business district in the downtown area of the city. It is home to Chicago's commercial core, City Hall, and the seat of Cook County. Bounded on the north and west by the Chicago River, on the east by Lake Michigan, and on the south by Roosevelt Road (although the commercial core has expanded into adjacent community areas), it is the second largest commercial business district in the United States after Midtown Manhattan and contains the headquarters of many locally and globally important businesses as well as many of Chicago's most famous attractions.",  photo: "The Loop", latitude: "41.875640", longitude: "-87.633073"),
    placesStruct(name: "Lincoln Park", textAbout: "  Lincoln Park is a designated community area on the North Side of Chicago, Illinois. Lying to the west of Lincoln Park, Chicago's largest park, it is one of the most affluent neighborhoods in Chicago. In 1824, the United States Army built a small post near today's Clybourn Avenue and Armitage Avenue (formerly Centre Street). Indian settlements existed along Green Bay Trail, now called Clark Street (named after George Rogers Clark), at the current intersection of Halsted Street and Fullerton Avenue. Before Green Bay Trail became Clark Street, it stretched as far as Green Bay, Wisconsin, including Sheridan Road",  photo: "Lincoln Park", latitude: "41.913983", longitude: "-87.630528"),
    placesStruct(name: "The Chicago Theatre", textAbout: "  Chicago's breath-taking National Landmark Theatre hosts concerts, comedians, theatrical productions and special events every year. The 3,600 seat auditorium is seven stories high, and the vertical 'C-H-I-C-A-G-O,' sign is one of the few such signs in existence today. A symbol of State Street and Chicago, the marquee is a landmark in itself, as is the Wurlitzer pipe organ. Patrons can also go behind-the-scenes on their educational venue tour, which runs a few times a week.",  photo: "The Chicago Theatre", latitude: "41.885282", longitude: "-87.627757"),
    placesStruct(name: "Chicago History Museum", textAbout: "  From Chicago's sports to politics, the Union Stockyards to the Great Chicago Fire - there's so much to explore at the Chicago History Museum. Dive right in with the Museum's exhibitions and programs or get out and explore the city through guided tours and events. Founded in 1856, the Chicago History Museum shares Chicago's stories, serving as a hub of scholarship and learning, inspiration and civic engagement. If you live in Chicago or visit here and are curious about the city's past, present and future, the museum should be your first stop.",  photo: "Chicago History Museum", latitude: "41.912267", longitude: "-87.632014"),
    placesStruct(name: "Chicago Skyline", textAbout: "  The buildings and architecture of Chicago have influenced and reflected the history of American architecture. The built environment of Chicago is reflective of the city's history and multicultural heritage, featuring prominent buildings in a variety of styles by many important architects. Since most structures within the downtown area were destroyed by the Great Chicago Fire in 1871 (the most famous exception being the Water Tower) Chicago buildings are noted for their originality rather than their antiquity.",  photo: "Chicago Skyline", latitude: "41.884528", longitude: "-87.619126"),
    placesStruct(name: "Goose Island Beer Co.", textAbout: "    Visit the Goose Island production brewery where we celebrate our craft, Chicago heritage, innovative spirit and our dedication to making great beer. Tap list varies day-to-day featuring rare, one-off beers you cant find anywhere else. Come in for a tour, or just sit back and enjoy a pint at the bar and even strike up a conversation with a Goose Island brewer! While we don't make food on-site, we do invite local food trucks over to park in front of the brewery.",  photo: "Goose Island Beer Co.", latitude: "41.891791", longitude: "-87.701656"),
    placesStruct(name: "Navy Pier", textAbout: "  Navy Pier is the place where all of Chicagoland and tourists from around the world have come together since 1995 to enjoy the beauty and the thrills of a day on Lake Michigan. From rides to restaurants, exhibitions to entertainment, shopping to dining cruises and tour boats Navy Pier has it all - in a location unlike any other!There's so much to do in our 50 acres of parks, promenades, gardens, shops, eateries and attractions.Take a ride on our 15-story Ferris wheel. Catch a movie at the IMAX® Theatre. Visit three floors of hands-on fun at the Chicago Children's Museum inside the Family Pavilion.",  photo: "Navy Pier", latitude: "41.892236", longitude: "-87.601068"),
    placesStruct(name: "Lincoln Park Conservatory", textAbout: "  Positioned near the shore of Lake Michigan, the Lincoln Park Conservatory (1.2 ha / 3 acres) is a conservatory and botanical garden in Lincoln Park in Chicago, Illinois. The conservatory is located at 2391 North Stockton Drive just south of Fullerton Avenue, west of Lake Shore Drive, and part of the Lincoln Park, Chicago community area. The Alfred Caldwell Lily Pool and the North Pond Nature Sanctuary are further to the north along Stockton Drive.",  photo: "Lincoln Park Conservatory", latitude: "41.924194", longitude: "-87.635612"),
    placesStruct(name: "Money Museum at the Federal Reserve Bank", textAbout: "  Where can you take your picture with a million bucks? Create your own currency? Try your hand at managing inflation? These are just some of the interactive activities available at the Money Museum at the Federal Reserve Bank of Chicago.We're open Monday to Friday from 8:30 a.m. to 5:00 p.m. (except Bank holidays, when we are closed). If you want to learn a bit more about the Fed, come for our 1 p.m. guided tour (allow about 45 minutes). Admission is always free.", photo: "Money Museum at the Federal Reserve Bank", latitude: "41.878247", longitude: "-87.632676"),
    placesStruct(name: "Crown Fountain", textAbout: "  Crown Fountain is an interactive work of public art and video sculpture featured in Chicago's Millennium Park, which is located in the Loop community area. Designed by Catalan artist Jaume Plensa and executed by Krueck and Sexton Architects, it opened in July 2004. The fountain is composed of a black granite reflecting pool placed between a pair of glass brick towers. The towers are 50 feet (15.2 m) tall, and they use light-emitting diodes (LEDs) to display digital videos on their inward faces. Construction and design of the Crown Fountain cost $17 million. ",  photo: "Crown Fountain", latitude: "41.881208", longitude: "-87.623728"),
    placesStruct(name: "Chicago Riverwalk", textAbout: "  The Chicago River is a system of rivers and canals with a combined length of 156 miles (251 km) that runs through the city of Chicago, including its center (the Chicago Loop). Though not especially long, the river is notable because it is one of the reasons for Chicago's geographic importance: the related Chicago Portage is a link between the Great Lakes and the Mississippi River Basin, and ultimately the Gulf of Mexico.The River is also noteworthy for its natural and human-engineered history.",  photo: "Chicago River", latitude: "41.888638", longitude: "-87.624911"),
    placesStruct(name: "The Rookery Building", textAbout: "  Set in the heart of Chicago’s financial district, Daniel Burnham and John Root’s 1888 Rookery Building is a Chicago landmark, containing one of Frank Lloyd Wright’s most dramatic interior compositions – a luminous and brilliantly articulated central light court. In 1905, Wright was commissioned to remodel the Rookery light court and lobbies. He realized a stunning balance between Burnham & Root’s ornamental ironwork and his own vision to create a spectacular environment.",  photo: "The Rookery Building", latitude: "41.879279", longitude: "-87.632131"),
    placesStruct(name: "Frank Lloyd Wright's Robie House", textAbout: "  The Robie House on the University of Chicago campus is considered one of the most important buildings in the history of American architecture. It was created by Frank Lloyd Wright for his client Frederick C. Robie, a forward-thinking businessman. Designed in Wright's Oak Park studio in 1908 and completed in 1910, the building is both a masterpiece of the Prairie style and renowned as a forerunner of modernism in architecture. ",  photo: "Frank Lloyd Wright's Robie House", latitude: "41.789729", longitude: "-87.595966"),
]

let textInfoLabel = "This application was written for tourists and local residents of Oslo. These places are required to visit! You can build a tourist route to the main attractions using the second screen. On the third screen you can offer an interesting place! Fill out the form and send it to us. If we like it too, then all users will see this place. You can also add your places in your application on the fourth screen. It will immediately appear on the map in your app."


struct myPlacesStruct {
    var text: String
    var longitude: String
    var latitude: String
    
    init(text: String, longitude: String, latitude: String) {
        self.text = text
        self.longitude = longitude
        self.latitude = latitude
    }
}
